apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fhd996007/fornetapp:v1
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://backend-service:8080"