---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
      - name: frontend
        image: fhd996007/11419:v1
        ports:
        - containerPort: 8080
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP